### PR TITLE
Update to 4.4.3

### PR DESCRIPTION
**Pull request by ebrehault**

### CODE REVIEW

**Comment by artursmirnov** [comment]
@ebrehault Thanks for your effort!

**Comment by ebrehault** [comment]
Thanks for merging it, but I am afraid the 4.4.3 tag has been dropped somehow (I did tag my commit and I did push it in my branch, but it looks like it is not on your master now).

**Comment by artursmirnov** [comment]
@ebrehault I have just pushed the tag and verified that it's on the repo.

**Comment by ebrehault** [comment]
Thank you :)

**Pull request merged**
