### PR TITLE
Update to TinyMCE 4.7.13

### PR DESCRIPTION
**Pull request by erral**
An update to the latest 4.8.1 will follow when this gets merged.

### CODE REVIEW

**Comment by erral** [comment]
Can someone look at this? @frapell ?

**Comment by frapell** [comment]
@erral Did you follow all the steps as detailed in the README? If so, you can merge it right away

**Comment by erral** [comment]
Yes, but I can't merge anything here.

**Comment by frapell** [comment]
@erral I'll merge it for you :)

@artursmirnov Could you give @erral access so he can merge the next one bringing 4.8.1? ;)

**Comment by frapell** [comment]
@erral BTW, I'm seeing they already released 4.8.3 are you bringing that one instead of 4.8.1 ?

**Comment by erral** [comment]
Of course, I will update 4.8.3 too.

**Comment by artursmirnov** [comment]
@frapell sure, sent an invite! @erral thanks for the contributions.

To be honest, I went far away from TinyMCE and unlikely would be able to get back some time soon. So probably it would be a good idea to transfer ownership to someone else.

**Comment by artursmirnov** [comment]
You can keep collaborating here if you prefer, I'm just not really capable to track TinyMCE updates and review PRs. But I'm open to give access to anyone as soon as you request.

**Pull request merged**
